name: API tests workflow
env:
  API_KEY: ${{ secrets.API_KEY }}
on:  
  workflow_dispatch:
  # workflow_run:
  #    workflows: [ deployWorkflow ]
  #    types:
  #       - completed
  # schedule:  
  #   - cron: "30 1 * * 1-5"  
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test --project="chromium" -g "@api"
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 1